# ONDC BAP Server - Production Configuration

[server]
host = "0.0.0.0"
port = 8442
request_timeout_secs = 30
max_connections = 10000

# TLS configuration (required for production)
[server.tls]
cert_path = "/opt/ssl-certs/fullchain.pem"
key_path = "/opt/ssl-certs/privkey.pem"

[ondc]
environment = "production"
registry_base_url = "https://network.lootai.co"
subscriber_id = "network.lootai.co"
callback_url = "/"
request_timeout_secs = 30
max_retries = 5

[keys]
# These must be actual production keys
signing_private_key = "your-production-signing-private-key-base64"
encryption_private_key = "your-production-encryption-private-key-base64"
unique_key_id = "prod_key_1"

[security]
enable_rate_limiting = true
max_requests_per_minute = 1000
enable_cors = true
allowed_origins = ["*"] 