# ONDC BAP Server - Staging Configuration

[server]
host = "0.0.0.0"
port = 8080
request_timeout_secs = 30
max_connections = 1000

# TLS configuration (optional for staging)
# [server.tls]
# cert_path = "certs/server.crt"
# key_path = "certs/server.key"

[ondc]
environment = "staging"
registry_base_url = "https://staging.registry.ondc.org"
subscriber_id = "your-domain.com"
callback_url = "/"
request_timeout_secs = 30
max_retries = 3

[keys]
# These should be replaced with actual keys in production
signing_private_key = "your-signing-private-key-base64"
encryption_private_key = "your-encryption-private-key-base64"
unique_key_id = "key_1"

[security]
enable_rate_limiting = true
max_requests_per_minute = 100
enable_cors = true
allowed_origins = ["*"] 