# ONDC BAP Server - Staging Configuration

[server]
host = "0.0.0.0"
port = 8443
request_timeout_secs = 30
max_connections = 1000

# TLS configuration (optional for staging)
# [server.tls]
# cert_path = "certs/server.crt"
# key_path = "certs/server.key"

[ondc]
environment = "staging"
registry_base_url = "https://staging.registry.ondc.org"
subscriber_id = "network.lootai.co"
callback_url = "/"
request_timeout_secs = 30
max_retries = 3

# Business entity configuration
[ondc.business_entity]
name_of_authorised_signatory = "Test Signatory"
address_of_authorised_signatory = "Test Address, Test City, Test State 123456"
email_id = "mrunalpendem123@gmail.com"
mobile_no = 8309084438
country = "IND"

[ondc.business_entity.gst]
legal_entity_name = "LootAI"
business_address = "Test Business Address, Test City, Test State 123456"
city_code = ["std:080"]
gst_no = "00AAAAA0000A1Z5"

[ondc.business_entity.pan]
name_as_per_pan = "PENDEM SAI SIVA SURYA MRUNAL"
pan_no = "GONPM8506J"
date_of_incorporation = "01/01/2025"

# Network participant configuration
[[ondc.network_participants]]
subscriber_url = "/"
domain = "nic2004:52110"
participant_type = "buyerApp"
msn = false
city_code = ["std:080"]

[keys]
# These should be replaced with actual keys in production
signing_private_key = "iblY/8ruRp43aGEjuCtJrs5QyAhaHroQIaUgWKNScco="
encryption_private_key = "zBxXRXJu+ny+1Ux5bjbp5AFoiYae9STWl10zIR/DRKU="
unique_key_id = "key_1"

[security]
enable_rate_limiting = true
max_requests_per_minute = 100
enable_cors = true
allowed_origins = ["*"] 